#!/bin/bash

LYN_EVT=$1
FE8_SYM=$2

LYN_JUMP=$(grep '^ORG \$' $LYN_EVT)
if [ -z "$LYN_JUMP" ]
then
    exit 0
fi

echo ""
echo "// lyn protectors"
echo "// Auto generated by $0"
echo ""

grep '^ORG \$' $LYN_EVT | while read -r line
do
    _addr=$(echo $line | awk '{print substr($2, 2)}')
    addr=$(printf "%08X" $((0x$_addr + 0x08000000)))

    SYM_REF=$(grep -A 1 $addr $FE8_SYM)
    length=$(echo $SYM_REF | awk '{ printf "%x\n", strtonum("0x"$3) - strtonum("0x"$1) }')

    echo "PROTECT 0x$_addr 0x$_addr + 0x$length // $(echo $SYM_REF | awk '{print $2}')"
done
