#!/usr/bin/python3

import sys

def main(args):
    print(f'\n@ Auto generated by {args[0]}')

    for line in sys.stdin.readlines():
        print(f"dat 0x{line[0:8]}, {line[11:-1]}")

if __name__ == '__main__':
    main(sys.argv)
