#!/usr/bin/python3

import sys

def main(args):

    print(f'\n// Auto generated by {args[0]}')

    for line in sys.stdin.readlines():
        print(f"#define {line[11:-1]} 0x{line[0:8]}")

    print("")

if __name__ == '__main__':
    main(sys.argv)
