#!/bin/bash

CHECK_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(c|h)$")

if [ -z "$CHECK_FILES" ]; then
    echo "No C files to check."
    exit 0
fi

ret=0

for file in $CHECK_FILES; do
    perl ./Tools/check_patch/checkpatch.pl --no-tree --file "$file"
    if [ $? -ne 0 ]; then
        echo "Code style issues found in $file."
        ret=1
    fi
done

if [ $ret -ne 0 ]; then
    echo "pre-commit check error!"
fi

# exit $ret
