#ifndef CONFIG_EFX_SKILLS_INSTALLED
#define CONFIG_EFX_SKILLS_INSTALLED

#include "efx-anim.h"

enum EfxSkillIndex {
    EFX_SKILL_DEFAULT = 0x1,
    EFX_COMBAT_DEFAULT,
    EFX_SKILL_MOKHA,
    EFX_SKILL_AETHER,
    EFX_SKILL_DRAGON_FANG,

    EFX_SKILL_MAX
};

#endif
