#pragma once

/* Auto generated by: make icon */
#include "../../Contents/Gfx/GfxDefs.h"

extern unsigned char const *const gpGFX_SkillIcon_WIP;
extern unsigned char const *const gpGFX_CombatArtIcon_SwordArtAtk;
extern unsigned char const *const gpGFX_CombatArtIcon_LanceArtAtk;
extern unsigned char const *const gpGFX_CombatArtIcon_AxeArtAtk;
extern unsigned char const *const gpGFX_CombatArtIcon_BowArtAtk;
