#include "common-chax.h"
#include "class-types.h"

const u8 KernelClassList_Flier[] = {
	CLASS_PEGASUS_KNIGHT,
	CLASS_FALCON_KNIGHT,
	CLASS_WYVERN_RIDER,
	CLASS_WYVERN_RIDER_F,
	CLASS_WYVERN_LORD,
	CLASS_WYVERN_LORD_F,
	CLASS_WYVERN_KNIGHT,
	CLASS_WYVERN_KNIGHT_F,
	CLASS_GARGOYLE,
	CLASS_DEATHGOYLE,
	CLASS_DEATHGOYLE,
	CLASS_MANAKETE_2,
	CLASS_MANAKETE_MYRRH,
	CLASS_DRACO_ZOMBIE,
	CLASS_NONE
};

const u8 KernelClassList_Cavalry[] = {
	CLASS_TROUBADOUR,
	CLASS_VALKYRIE,
	CLASS_CAVALIER,
	CLASS_CAVALIER_F,
	CLASS_PALADIN,
	CLASS_PALADIN_F,
	CLASS_RANGER,
	CLASS_RANGER_F,
	CLASS_MAGE_KNIGHT,
	CLASS_MAGE_KNIGHT_F,
	CLASS_GREAT_KNIGHT,
	CLASS_GREAT_KNIGHT_F,
	CLASS_TARVOS,
	CLASS_MAELDUIN,
	CLASS_EPHRAIM_MASTER_LORD,
	CLASS_EIRIKA_MASTER_LORD,
	CLASS_NONE
};

const u8 KernelClassList_Armor[] = {
	CLASS_ARMOR_KNIGHT,
	CLASS_ARMOR_KNIGHT_F,
	CLASS_GENERAL,
	CLASS_GENERAL_F,
	CLASS_GREAT_KNIGHT,
	CLASS_GREAT_KNIGHT_F,
	CLASS_NONE
};

const u8 KernelClassList_Dragon[] = {
	CLASS_WYVERN_RIDER,
	CLASS_WYVERN_RIDER_F,
	CLASS_WYVERN_LORD,
	CLASS_WYVERN_LORD_F,
	CLASS_WYVERN_KNIGHT,
	CLASS_WYVERN_KNIGHT_F,
	CLASS_MANAKETE_2,
	CLASS_MANAKETE_MYRRH,
	CLASS_DRACO_ZOMBIE,
	CLASS_MANAKETE_2,
	CLASS_MANAKETE_MYRRH,
	CLASS_NONE
};

const u8 KernelClassList_Beast[] = {
	CLASS_REVENANT,
	CLASS_ENTOUMBED,
	CLASS_BONEWALKER,
	CLASS_BONEWALKER_BOW,
	CLASS_WIGHT,
	CLASS_WIGHT_BOW,
	CLASS_BAEL,
	CLASS_ELDER_BAEL,
	CLASS_CYCLOPS,
	CLASS_MAUTHEDOOG,
	CLASS_GWYLLGI,
	CLASS_TARVOS,
	CLASS_MAELDUIN,
	CLASS_MOGALL,
	CLASS_ARCH_MOGALL,
	CLASS_GORGON,
	CLASS_GORGONEGG,
	CLASS_GARGOYLE,
	CLASS_DEATHGOYLE,
	CLASS_DRACO_ZOMBIE,
	CLASS_DEMON_KING,
	CLASS_MANAKETE_2,
	CLASS_CYCLOPS_2,
	CLASS_ELDER_BAEL_2,
	CLASS_PHANTOM,
	CLASS_NONE
};
