#!/bin/bash

SOURCE_DIR=Sources
INSTALLER=$2
HEADER=$1

rm -f $INSTALLER $HEADER

SCR_NAME=$(basename $0)
DAY_TIME=$(date "+%Y-%m-%d %H:%M:%S")

echo -e "// Auto generated by $SCR_NAME at $DAY_TIME\n" > $INSTALLER
echo -e "// Auto generated by $SCR_NAME at $DAY_TIME\n" > $HEADER

echo -e "#ifndef GFX_CONFIG_INSTALLED" >> $HEADER
echo -e "#define GFX_CONFIG_INSTALLED\n" >> $HEADER

all_sources=$(find $SOURCE_DIR -type f -name "*.png")

for file in $all_sources; do
    base_name=$(echo ${file#*/} | sed 's/\.png//; s/\//_/g')
    target=$(echo $file | sed 's/\.png/\.4bpp/')
    echo -e "ALIGN 4\nGFX_$base_name:\n\t#incbin \"$target\"\n" >> $INSTALLER
    echo -e "extern const unsigned char GFX_$base_name[];" >> $HEADER
done

echo -e "\n#endif /* GFX_CONFIG_INSTALLED */" >> $HEADER
