/* Generated by re2c 3.0 on Thu May 23 20:12:13 2024 */
#line 1 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"

#include "parser.h"

Includes parse_includes(const std::string& fileContents)
{
	Includes result;

	auto cursor = fileContents.cbegin(), marker = fileContents.cbegin();

	#line 20 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"


	const auto skip_line_comment = [&] ()
	{
		while (true)
		{
			
#line 21 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
{
	std::string::value_type yych;
	yych = *cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\n': goto yy3;
		default: goto yy2;
	}
yy1:
	++cursor;
#line 29 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return; }
#line 34 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy2:
	++cursor;
#line 28 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ continue; }
#line 39 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy3:
	++cursor;
#line 30 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return; }
#line 44 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
}
#line 32 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"

		}
	};

	const auto skip_multi_comment = [&] () -> bool
	{
		unsigned depth = 1;

		while (true)
		{
			
#line 58 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
{
	std::string::value_type yych;
	yych = *cursor;
	switch (yych) {
		case 0x00: goto yy5;
		case '*': goto yy8;
		case '/': goto yy9;
		default: goto yy6;
	}
yy5:
	++cursor;
#line 44 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return false; }
#line 72 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy6:
	++cursor;
yy7:
#line 45 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ continue; }
#line 78 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy8:
	yych = *++cursor;
	switch (yych) {
		case '/': goto yy10;
		default: goto yy7;
	}
yy9:
	yych = *++cursor;
	switch (yych) {
		case '*': goto yy11;
		default: goto yy7;
	}
yy10:
	++cursor;
#line 48 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ if ((--depth) == 0) return true; }
#line 95 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy11:
	++cursor;
#line 47 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ ++depth; }
#line 100 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
}
#line 50 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"

		}
	};

	const auto get_included_file = [&] () -> std::string
	{
		const auto token = cursor;

		
#line 112 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
{
	std::string::value_type yych;
	yych = *cursor;
	switch (yych) {
		case 0x00: goto yy13;
		case '\t':
		case '\n':
		case '\v':
		case '\r':
		case ' ': goto yy17;
		case '"': goto yy18;
		default: goto yy15;
	}
yy13:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\r':
		case ' ':
		case '"': goto yy14;
		default: goto yy15;
	}
yy14:
#line 61 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return {}; }
#line 140 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy15:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\r':
		case ' ':
		case '"': goto yy16;
		default: goto yy15;
	}
yy16:
#line 67 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return std::string(token, cursor); }
#line 155 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy17:
	++cursor;
#line 60 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return {}; }
#line 160 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy18:
	yych = *++cursor;
	switch (yych) {
		case '"': goto yy19;
		default: goto yy18;
	}
yy19:
	++cursor;
#line 64 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return std::string(token + 1, cursor - 1); }
#line 171 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
}
#line 69 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"

	};

	while (cursor <= fileContents.cend())
	{
		
#line 180 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
{
	std::string::value_type yych;
	yych = *cursor;
	switch (yych) {
		case 0x00: goto yy21;
		case '#': goto yy24;
		case '/': goto yy25;
		default: goto yy22;
	}
yy21:
	++cursor;
#line 77 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ return result; }
#line 194 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy22:
	++cursor;
yy23:
#line 76 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ continue; }
#line 200 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy24:
	yych = *(marker = ++cursor);
	switch (yych) {
		case 'i': goto yy26;
		default: goto yy23;
	}
yy25:
	yych = *++cursor;
	switch (yych) {
		case '*': goto yy28;
		case '/': goto yy29;
		default: goto yy23;
	}
yy26:
	yych = *++cursor;
	switch (yych) {
		case 'n': goto yy30;
		default: goto yy27;
	}
yy27:
	cursor = marker;
	goto yy23;
yy28:
	++cursor;
#line 80 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ skip_multi_comment(); continue; }
#line 227 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy29:
	++cursor;
#line 79 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ skip_line_comment(); continue; }
#line 232 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy30:
	yych = *++cursor;
	switch (yych) {
		case 'c': goto yy31;
		default: goto yy27;
	}
yy31:
	yych = *++cursor;
	switch (yych) {
		case 'b': goto yy32;
		case 'l': goto yy33;
		default: goto yy27;
	}
yy32:
	yych = *++cursor;
	switch (yych) {
		case 'i': goto yy34;
		default: goto yy27;
	}
yy33:
	yych = *++cursor;
	switch (yych) {
		case 'u': goto yy35;
		default: goto yy27;
	}
yy34:
	yych = *++cursor;
	switch (yych) {
		case 'n': goto yy36;
		default: goto yy27;
	}
yy35:
	yych = *++cursor;
	switch (yych) {
		case 'd': goto yy38;
		default: goto yy27;
	}
yy36:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\r':
		case ' ': goto yy36;
		default: goto yy37;
	}
yy37:
#line 83 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ result.incbinFiles.push_back(get_included_file()); continue; }
#line 282 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
yy38:
	yych = *++cursor;
	switch (yych) {
		case 'e': goto yy39;
		default: goto yy27;
	}
yy39:
	yych = *++cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\r':
		case ' ': goto yy39;
		default: goto yy40;
	}
yy40:
#line 82 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"
	{ result.includeFiles.push_back(get_included_file()); continue; }
#line 301 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.cpp"
}
#line 85 "/mnt/c/Users/Owner/Desktop/Gaming/Nintendo/Game_Boy_Advance/FE8/fe8u-cskillsys-kernel/Tools/EventAssembler/.Sources/ea-dep/parser.repp"

	}

	return result;
}
