#include "common-chax.h"
#include "battle-system.h"

const u8 BattleUnwindConfig[14][4] = {
    { ACT_ATTACK, TAR_ATTACK, NOP_ATTACK, NOP_ATTACK }, // 0:default
    { TAR_ATTACK, ACT_ATTACK, NOP_ATTACK, NOP_ATTACK }, // 1   = 1
    { ACT_ATTACK, ACT_ATTACK, TAR_ATTACK, NOP_ATTACK }, // 2   = 2    

    { TAR_ATTACK, ACT_ATTACK, ACT_ATTACK, NOP_ATTACK }, // 12  = 3
    { ACT_ATTACK, TAR_ATTACK, ACT_ATTACK, NOP_ATTACK }, // 3   = 4
    { TAR_ATTACK, ACT_ATTACK, ACT_ATTACK, NOP_ATTACK }, // 13  = 5
    { ACT_ATTACK, TAR_ATTACK, NOP_ATTACK, NOP_ATTACK }, // 0:default
    { ACT_ATTACK, TAR_ATTACK, NOP_ATTACK, NOP_ATTACK }, // 0:default
    { ACT_ATTACK, TAR_ATTACK, TAR_ATTACK, NOP_ATTACK }, // 4   = 8
    { TAR_ATTACK, ACT_ATTACK, TAR_ATTACK, NOP_ATTACK }, // 14  = 9
    { ACT_ATTACK, ACT_ATTACK, TAR_ATTACK, TAR_ATTACK }, // 24  = 10

    { TAR_ATTACK, ACT_ATTACK, ACT_ATTACK, TAR_ATTACK }, // 124 = 11
    { ACT_ATTACK, TAR_ATTACK, ACT_ATTACK, TAR_ATTACK }, // 34  = 12
    { TAR_ATTACK, ACT_ATTACK, TAR_ATTACK, ACT_ATTACK }  // 134 = 13
};

const u16 DmgDecreaseRef[DMG_DECREASE_IDX_MAX] = {
    [DMG_DECREASE_IDX_05Perc] = DMG_DECREASE_05Perc,
    [DMG_DECREASE_IDX_10Perc] = DMG_DECREASE_10Perc,
    [DMG_DECREASE_IDX_15Perc] = DMG_DECREASE_15Perc,
    [DMG_DECREASE_IDX_20Perc] = DMG_DECREASE_20Perc,
    [DMG_DECREASE_IDX_25Perc] = DMG_DECREASE_25Perc,
    [DMG_DECREASE_IDX_30Perc] = DMG_DECREASE_30Perc,
    [DMG_DECREASE_IDX_35Perc] = DMG_DECREASE_35Perc,
    [DMG_DECREASE_IDX_40Perc] = DMG_DECREASE_40Perc,
    [DMG_DECREASE_IDX_45Perc] = DMG_DECREASE_45Perc,
    [DMG_DECREASE_IDX_50Perc] = DMG_DECREASE_50Perc,
    [DMG_DECREASE_IDX_55Perc] = DMG_DECREASE_55Perc,
    [DMG_DECREASE_IDX_60Perc] = DMG_DECREASE_60Perc,
    [DMG_DECREASE_IDX_65Perc] = DMG_DECREASE_65Perc,
    [DMG_DECREASE_IDX_70Perc] = DMG_DECREASE_70Perc,
    [DMG_DECREASE_IDX_75Perc] = DMG_DECREASE_75Perc,
    [DMG_DECREASE_IDX_80Perc] = DMG_DECREASE_80Perc,
    [DMG_DECREASE_IDX_85Perc] = DMG_DECREASE_85Perc,
    [DMG_DECREASE_IDX_90Perc] = DMG_DECREASE_90Perc,
    [DMG_DECREASE_IDX_95Perc] = DMG_DECREASE_95Perc,
};
